mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls')),
    path('shop/', include('shop.urls')),
]

post/urls.py
from django.urls import path
from . import views


app_name = 'post'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('post/<pk>', views.post, name='post'),
    path('user/<pk>', views.user, name='user'),
    path('post/<pk>/like',views.like, name='like'),
    path('user/<pk>/follow', views.follow, name='follow'),
    path('new_post', views.new_post, name='new_post'),
    path('post/<pk>/edit', views.edit_post, name='edit_post'),
    path('post/<pk>/delete', views.delete_post, name='delete_post')
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.index, name='index'),
    path('<pk>/', views.item, name='item')
]

post/models.py
from django.db import models
from django.utils import timezone

class User(models.Model):
    username = models.CharField(max_length=15)
    profile_description = models.TextField()
    created_date = models.DateTimeField()
    followers_count = models.IntegerField(default=0)

    def __str__(self):
        return self.username


class Post(models.Model):
    who_wrote_it = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    posted_date = models.DateTimeField()
    like_count = models.IntegerField(default=0)

    def __str__(self):
        return self.title

shop/models.py
from django.db import models
from post.models import User
from django.template.defaultfilters import slugify

class Item(models.Model):
    name = models.CharField(max_length = 100)
    price = models.IntegerField()
    description = models.TextField()
    who_sold_it = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.name

post/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

post/views.py
from django.shortcuts import render, redirect
from .models import Post, User
from .forms import PostForm
from django.utils import timezone


def homepage(request):
    posts = Post.objects.all()
    return render(request, 'post/homepage.html', {'posts':posts})

def post(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'post/wpis.html', {'post':post})

def user(request, pk):
    user = User.objects.get(pk=pk)
    posts = user.post_set.all()
    return render(request, 'post/user.html', {'user': user, 'posts': posts})

def like(request, pk):
    post = Post.objects.get(pk=pk)
    post.like_count += 1
    post.save()
    return redirect('post:post', pk=post.pk)

def follow(request, pk):
    user = User.objects.get(pk=pk)
    user.followers_count += 1
    user.save()
    return redirect('post:user', pk=user.pk)

def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit = False)
            post.posted_date = timezone.now()
            post.who_wrote_it = User.objects.get(pk=1)
            post.save()
            return redirect('post', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'post/new_post.html', {'form':form})

def edit_post(request, pk):
    post = Post.objects.get(pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'post/new_post.html', {'form': form})

def delete_post(request, pk):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('homepage')

shop/views.py
from django.shortcuts import render
from .models import Item

def index(request):
    items = Item.objects.all()
    return render(request, 'shop/index.html', {'items': items})

def item(request, pk):
    item = Item.objects.get(pk=pk)
    item.views += 1
    item.save()
    return render(request, 'shop/item.html', {'item': item})

templates/post/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Homepage</title>

    <style>
        body{
            background:rgba(30,30,255,0.5);
        }
        h1{
            font-family: 'Times New Roman', Times, serif;
            
        }
        h1 a{
            text-decoration: none;
            color:rgb(30,30,255);
    
        }
    
        hr{
            color:black
        }

        a{
            text-decoration: none;
            color:rgb(0, 0, 83);
        }

        a:hover{
            color: white;
           
        }
        .flex{
            display: flex;
            align-items: center;
        }
        .spacer{
            flex:1;
        }

        .button{
            text-align: center;
            border:none;
            border-radius:25px;
            width:120px;
            height:30px;
            transition: all .5s;
            color:black;
            cursor: pointer;
            background: white;
            padding-top:6px;
            transition:all 1s;
            font-family: 'Times New Roman', Times, serif;
        }

        .button:hover{
            background: black;
            color:white;
        }
        </style>    
</head>
<body>
    <div class="flex">
    <h1><a href="">Website</a> <a href="{% url 'shop:index' %}">Shop</a></h1>
    <div class="spacer"></div>
    <a class="button" href="{% url 'post:new_post' %}">New Post</a></p>
    </div>
    <hr>
    {% for post in posts %}
    <h2><b><a href="{% url 'post:post' pk=post.pk %}">{{post.title}}</a></b></h2>
    <p>{{post.text}}</p>
    <em><p>Added by: <a href="{% url 'post:user' pk=post.who_wrote_it.pk %}">{{post.who_wrote_it}}</a></p></em>
    <hr>
    {% endfor %}
</body>
</html>

templates/post/new_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <style>
        body{
            background:rgba(30,30,255,0.5);
        }
        h1{
            font-family: 'Times New Roman', Times, serif;
            
        }
        h1 a{
            text-decoration: none;
            color:rgb(30,30,255);
            transition: all 0.5s;
    
        }
    
        h1 a:hover{
            color:white;
        }
        hr{
            color:black;
        }
        </style>
</head>
<body>
    <h1><a href="/">Twitter</a></h1>
    <hr>
        <h2>New post</h2>
        <form method="POST">{% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Save</button>
        </form>
</body>
</html>

templates/post/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{user.username}}</title>
    <style>
        body{
            background:rgba(30,30,255,0.5);
        }
        h1{
            font-family: 'Times New Roman', Times, serif;
            text-transform: uppercase;
        }
        h1 a{
            text-decoration: none;
            color:rgb(30,30,255);
            transition: all 0.5s;

        }

        h1 a:hover{
            color:white;
        }

        h2{
            text-transform: uppercase;  
        }

        .followBTN{
            border:none;
            border-radius:25px;
            width:90px;
            height:30px;
            transition: all .5s;
            color:black;
            cursor: pointer;
        }

        .followBTN:hover{
            background:rgba(0,0,0,0.9);
            color:white;
        }

        hr{
            color:black;
        }
        

    </style>  
</head>
<body>
    <h1><a href="/">Twitter</a></h1>
    <hr>
    
        <h2>{{user.username}}</h2>
        <p>{{user.profile_description}}</p>
        <p>Profile created in {{user.created_date}}</p>

        <p>Followers count: <b>{{user.followers_count}}</b></p>
        <form action="{% url 'post:follow' user.pk %}">
            {% csrf_token %}
            <input class="followBTN" type="submit" value="follow" />
        </form>

    
    <h2>POSTS</h2>
   
    {% for post in posts %}
        <div style="border:1px solid black" class='ramka'></div>
            <h3><a href="{% url 'post:post' pk=post.pk %}">{{post.title}}</a></h3>
            <p>{{post.text}}</p>
            <p> Published in: {{post.posted_date}}</p>
            <p>{{post.like_count}} likes</p>
        </div>
        
    {% endfor %}


</body>
</html>

templates/post/wpis.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <style>
    body{
        background:rgba(30,30,255,0.5);
    }
    h1{
        font-family: 'Times New Roman', Times, serif;
        
    }
    h1 a{
        text-decoration: none;
        color:rgb(30,30,255);
        transition: all 0.5s;

    }

    h1 a:hover{
        color:white;
    }
    hr{
        color:black;
    }

    .lickBTN{
        border:none;
        border-radius:25px;
        width:90px;
        height:30px;
        transition: all .5s;
        color:black;
        cursor: pointer;
    }

    .lickBTN:hover{
        background:rgba(0,0,0,0.9);
        color:white;
    }
    </style>
</head>
<body>
    <h1><a href="/">Twitter</a></h1>
    <hr>
    <b><h2>{{post.title}}</h2></b>
    <p><a href="{% url 'post:edit_post' post.pk %}">Edit Post</a></p>
    <p>{{post.text}}</p>
    <form action="{%url 'post:like' post.pk%}">
            {%csrf_token%}
            <input type="submit" class='lickBTN' value="lick" />
    </form>

    <p>LIKE COUNT: {{post.like_count}}</p>
    <em><p>Post published in: {{post.posted_date}} by <a href="{% url 'post:user' pk=post.who_wrote_it.pk %}">{{post.who_wrote_it}}</a></p></em>

    <script>
        let lick = document.querySelector('.lickBTN');

        lick.addEventListener('click',function(){
            alert('You liked post');
        })
    </script>
    <form action='{% url "post:delete_post" post.pk %}'
    {%csrf_token%}
    <input type="submit" class='lickBTN' value="remove" />
    </form>
</body>
</html>

templates/shop/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1><a href="/">Twitter</a></h1>
    <h2>Przedmioty wystawione na sprzedaż</h2>
    {% for item in items %}
    <div>
    <h3><a href="{% url 'shop:item' pk=item.pk %}">{{item.name}}</a></h3>
    <p>{{item.description}}</p>
    <p><em>Price: {{item.price}} PLN</em></p>
    {% endfor %}

    </div>
</body>
</html>

templates/shop/item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1><a href="/">Twitter</a></h1>
    <h2>{{item.name}}</h2>
    <h4>{{item.description}}</h4>
    <p>Price: {{item.price}}</p>
    <p><em>Contact to seller: <a href="{% url 'post:user' pk=item.who_sold_it.pk %}">{{item.who_sold_it}}</a></em></p>
    <p>Views: {{item.views}}</p>
</body>
</html>